In [1]:
import numpy as np

In [4]:
lista = [1,2,3,4,5]

array = np.array(lista)

print(lista)
print(array)

print(type(lista))
print(type(array))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


In [5]:
arr_zeros = np.zeros(10)

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
array[0] = 9

print(array)

[9 2 3 4 5]


In [9]:
matriz_zeros = np.zeros((5,3))

print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
lista_de_notas = [9.8, 5.6, 7.4, 3.2, 8.5]

notas = np.array(lista_de_notas)

In [12]:
print('Máxima', notas.max())
print('Mínima', notas.min())
print('Desvio padrão', notas.std())
print('Média', notas.mean())
print('Posição da menor nota', notas.argmin()) #começa no 0

Máxima 9.8
Mínima 3.2
Desvio padrão 2.3065125189341593
Média 6.9
Posição da menor nota 3
